version: "3.8"

networks:
  video-storage-network:
    driver: bridge

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: databases-service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - video-storage-network

  redis:
    image: "redis"
    container_name: caching-service
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./data/redis:/data
    networks:
      - video-storage-network

  video-storage:
    container_name: video-storage-service
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    restart: on-failure
    tty: true
    ports:
      - "${VIDEO_STORAGE_SERVER_PORT}:${VIDEO_STORAGE_SERVER_PORT}"
    depends_on:
      - postgres
      - redis
    environment:
      MODE: video-storage
    env_file: .env
    volumes:
      - ./src:/srv/app/src
    networks:
      - video-storage-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

